import type { Booking } from '@rara/types';
import { BookingStatus, PaymentStatus } from '@rara/types';

export const SAMPLE_BOOKINGS: Booking[] = [
  {
    id: 'booking-1',
    clientId: 'client-1',
    serviceId: 'svc-2',
    stylistId: 'stylist-1',
    bookingDate: new Date('2026-05-30'),
    startTime: '10:00',
    endTime: '10:45',
    status: BookingStatus.CONFIRMED,
    paymentStatus: PaymentStatus.PAID,
    totalPrice: 100000,
    notes: 'Potong dan tata rambut',
    isActive: true,
    createdAt: new Date('2026-05-25'),
    updatedAt: new Date('2026-05-25'),
  },
  {
    id: 'booking-2',
    clientId: 'client-2',
    serviceId: 'svc-4',
    stylistId: 'stylist-1',
    bookingDate: new Date('2026-05-31'),
    startTime: '13:00',
    endTime: '15:00',
    status: BookingStatus.CONFIRMED,
    paymentStatus: PaymentStatus.PAID,
    totalPrice: 300000,
    notes: 'Full hair coloring - ash brown',
    isActive: true,
    createdAt: new Date('2026-05-25'),
    updatedAt: new Date('2026-05-25'),
  },
  {
    id: 'booking-3',
    clientId: 'client-3',
    serviceId: 'svc-8',
    stylistId: 'stylist-2',
    bookingDate: new Date('2026-06-01'),
    startTime: '14:00',
    endTime: '15:30',
    status: BookingStatus.PENDING,
    paymentStatus: PaymentStatus.UNPAID,
    totalPrice: 250000,
    notes: 'Hair spa dengan massage',
    isActive: true,
    createdAt: new Date('2026-05-24'),
    updatedAt: new Date('2026-05-24'),
  },
  {
    id: 'booking-4',
    clientId: 'client-4',
    serviceId: 'svc-1',
    stylistId: 'stylist-3',
    bookingDate: new Date('2026-05-28'),
    startTime: '09:00',
    endTime: '09:30',
    status: BookingStatus.COMPLETED,
    paymentStatus: PaymentStatus.PAID,
    totalPrice: 50000,
    notes: '',
    isActive: true,
    createdAt: new Date('2026-05-20'),
    updatedAt: new Date('2026-05-28'),
  },
  {
    id: 'booking-5',
    clientId: 'client-5',
    serviceId: 'svc-11',
    stylistId: 'stylist-4',
    bookingDate: new Date('2026-06-15'),
    startTime: '10:00',
    endTime: '11:30',
    status: BookingStatus.CONFIRMED,
    paymentStatus: PaymentStatus.PARTIALLY_PAID,
    totalPrice: 400000,
    notes: 'Wedding styling - bride',
    isActive: true,
    createdAt: new Date('2026-05-25'),
    updatedAt: new Date('2026-05-25'),
  },
];
