export enum Permission {
  // Dashboard
  VIEW_DASHBOARD = 'VIEW_DASHBOARD',
  MANAGE_DASHBOARD = 'MANAGE_DASHBOARD',

  // Bookings
  VIEW_BOOKINGS = 'VIEW_BOOKINGS',
  CREATE_BOOKINGS = 'CREATE_BOOKINGS',
  EDIT_BOOKINGS = 'EDIT_BOOKINGS',
  DELETE_BOOKINGS = 'DELETE_BOOKINGS',

  // Clients
  VIEW_CLIENTS = 'VIEW_CLIENTS',
  EDIT_CLIENTS = 'EDIT_CLIENTS',
  DELETE_CLIENTS = 'DELETE_CLIENTS',

  // Services
  VIEW_SERVICES = 'VIEW_SERVICES',
  MANAGE_SERVICES = 'MANAGE_SERVICES',

  // Users
  VIEW_USERS = 'VIEW_USERS',
  MANAGE_USERS = 'MANAGE_USERS',

  // Settings
  VIEW_SETTINGS = 'VIEW_SETTINGS',
  MANAGE_SETTINGS = 'MANAGE_SETTINGS'
}

export type PermissionSet = Partial<Record<Permission, boolean>>;
