import type { Service } from '@rara/types';

export const SALON_SERVICES: Service[] = [
  // Potong Rambut
  {
    id: 'svc-1',
    name: 'Basic Haircut',
    categoryId: 'cat-1',
    description: 'Potong rambut standar dengan potongan yang rapi',
    duration: 30,
    price: 50000,
    isActive: true,
    maxCapacity: 1,
    displayOrder: 1,
  },
  {
    id: 'svc-2',
    name: 'Premium Haircut',
    categoryId: 'cat-1',
    description: 'Potong rambut premium dengan konsultasi gaya',
    duration: 45,
    price: 100000,
    isActive: true,
    maxCapacity: 1,
    displayOrder: 2,
  },
  {
    id: 'svc-3',
    name: 'Children Haircut',
    categoryId: 'cat-1',
    description: 'Potong rambut khusus anak-anak',
    duration: 20,
    price: 35000,
    isActive: true,
    maxCapacity: 1,
    displayOrder: 3,
  },

  // Coloring
  {
    id: 'svc-4',
    name: 'Hair Coloring - Full',
    categoryId: 'cat-2',
    description: 'Pewarnaan rambut seluruh kepala',
    duration: 120,
    price: 300000,
    isActive: true,
    maxCapacity: 1,
    displayOrder: 4,
  },
  {
    id: 'svc-5',
    name: 'Balayage',
    categoryId: 'cat-2',
    description: 'Teknik pewarnaan gradasi halus',
    duration: 150,
    price: 400000,
    isActive: true,
    maxCapacity: 1,
    displayOrder: 5,
  },
  {
    id: 'svc-6',
    name: 'Root Touch Up',
    categoryId: 'cat-2',
    description: 'Pewarnaan ulang bagian akar',
    duration: 60,
    price: 150000,
    isActive: true,
    maxCapacity: 1,
    displayOrder: 6,
  },

  // Perawatan Rambut
  {
    id: 'svc-7',
    name: 'Deep Conditioning',
    categoryId: 'cat-3',
    description: 'Perawatan intensif untuk rambut kering dan rusak',
    duration: 60,
    price: 150000,
    isActive: true,
    maxCapacity: 2,
    displayOrder: 7,
  },
  {
    id: 'svc-8',
    name: 'Hair Spa',
    categoryId: 'cat-3',
    description: 'Spa rambut lengkap dengan massage kulit kepala',
    duration: 90,
    price: 250000,
    isActive: true,
    maxCapacity: 1,
    displayOrder: 8,
  },
  {
    id: 'svc-9',
    name: 'Keratin Treatment',
    categoryId: 'cat-3',
    description: 'Perawatan keratin untuk rambut lebih lurus dan mengkilap',
    duration: 120,
    price: 350000,
    isActive: true,
    maxCapacity: 1,
    displayOrder: 9,
  },

  // Styling
  {
    id: 'svc-10',
    name: 'Blow Dry Styling',
    categoryId: 'cat-4',
    description: 'Styling rambut dengan teknik blow dry',
    duration: 45,
    price: 120000,
    isActive: true,
    maxCapacity: 1,
    displayOrder: 10,
  },
  {
    id: 'svc-11',
    name: 'Wedding Styling',
    categoryId: 'cat-4',
    description: 'Styling khusus untuk acara pernikahan',
    duration: 90,
    price: 400000,
    isActive: true,
    maxCapacity: 1,
    displayOrder: 11,
  },
  {
    id: 'svc-12',
    name: 'Bridal Trial',
    categoryId: 'cat-4',
    description: 'Percobaan styling pengantin sebelum hari H',
    duration: 60,
    price: 300000,
    isActive: true,
    maxCapacity: 1,
    displayOrder: 12,
  },

  // Perawatan Kulit Kepala
  {
    id: 'svc-13',
    name: 'Scalp Treatment',
    categoryId: 'cat-5',
    description: 'Perawatan intensif untuk kulit kepala sensitif',
    duration: 45,
    price: 150000,
    isActive: true,
    maxCapacity: 1,
    displayOrder: 13,
  },
  {
    id: 'svc-14',
    name: 'Anti-Dandruff Treatment',
    categoryId: 'cat-5',
    description: 'Treatment khusus mengatasi ketombe',
    duration: 50,
    price: 180000,
    isActive: true,
    maxCapacity: 1,
    displayOrder: 14,
  },
];
