import type { UserProfile } from '@rara/types';
import { UserRole } from '@rara/types';

export const SALON_STYLISTS: UserProfile[] = [
  {
    id: 'stylist-1',
    name: 'Siti Nurhaliza',
    email: 'siti@raraSalon.com',
    role: UserRole.STYLIST,
    phone: '+62812345678',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=siti',
    isActive: true,
    createdAt: new Date('2023-01-15'),
    updatedAt: new Date('2024-01-15'),
    bio: 'Senior stylist dengan pengalaman 8 tahun, spesialis coloring dan styling',
    specialties: ['Hair Coloring', 'Styling', 'Balayage'],
  },
  {
    id: 'stylist-2',
    name: 'Rina Wijaya',
    email: 'rina@raraSalon.com',
    role: UserRole.STYLIST,
    phone: '+62812345679',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=rina',
    isActive: true,
    createdAt: new Date('2023-03-20'),
    updatedAt: new Date('2024-01-15'),
    bio: 'Profesional perawatan rambut, ahli dalam hair treatment dan keratin',
    specialties: ['Hair Treatment', 'Keratin Treatment', 'Deep Conditioning'],
  },
  {
    id: 'stylist-3',
    name: 'Budi Santoso',
    email: 'budi@raraSalon.com',
    role: UserRole.STYLIST,
    phone: '+62812345680',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=budi',
    isActive: true,
    createdAt: new Date('2023-06-10'),
    updatedAt: new Date('2024-01-15'),
    bio: 'Spesialis potong rambut pria dan barbering, 5 tahun pengalaman',
    specialties: ['Haircut', 'Barbering', 'Men Styling'],
  },
  {
    id: 'stylist-4',
    name: 'Maya Dewi',
    email: 'maya@raraSalon.com',
    role: UserRole.STYLIST,
    phone: '+62812345681',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=maya',
    isActive: true,
    createdAt: new Date('2023-07-05'),
    updatedAt: new Date('2024-01-15'),
    bio: 'Expert dalam wedding styling dan bridal makeup, telah menangani 50+ pernikahan',
    specialties: ['Wedding Styling', 'Bridal Makeup', 'Event Styling'],
  },
  {
    id: 'stylist-5',
    name: 'Dina Lestari',
    email: 'dina@raraSalon.com',
    role: UserRole.STYLIST,
    phone: '+62812345682',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=dina',
    isActive: true,
    createdAt: new Date('2023-09-12'),
    updatedAt: new Date('2024-01-15'),
    bio: 'Spesialis scalp treatment dan perawatan kulit kepala sensitif',
    specialties: ['Scalp Treatment', 'Anti-Dandruff', 'Hair Spa'],
  },
];
