/**
 * @responsibility
 * DEV-only mock data for the overview page.
 * Simulates data that will come from the database/API in production.
 *
 * @usedBy
 * use-booking-list (manualBookings initial state)
 * use-walk-in-flow (MOCK_SERVICES, MOCK_PRODUCTS)
 *
 * @notes
 * TODO: Remove this file once real API endpoints are connected.
 * MOCK_SERVICES and MOCK_PRODUCTS should come from the Settings API.
 * DUMMY_BOOKINGS should be removed entirely in production.
 */

import type { DashboardBooking } from '@/features/dashboard/types/dashboard.types';
import type { MockService, MockProduct } from '@/features/dashboard/types/overview.types';

const _TODAY = new Date().toISOString().slice(0, 10);

export const DUMMY_BOOKINGS: DashboardBooking[] = [
  {
    id: 'dummy-1',
    bookingCode: 'BK-D001',
    customerName: 'Siti Rahayu',
    customerPhone: '081234561001',
    serviceName: 'Haircut & Blow Dry',
    categoryName: 'Hair',
    stylistName: 'Maya Putri',
    stylistInitials: 'MP',
    stylistColor: '#FF6B9D',
    date: _TODAY,
    timeSlot: '09:00:00',
    endTime: '10:00:00',
    duration: 60,
    price: 85000,
    status: 'CONFIRMED',
    visitorType: 'BOOKING',
    paymentStatus: 'DEPOSIT',
    addOns: [],
    notes: '',
  },
  {
    id: 'dummy-2',
    bookingCode: 'BK-D002',
    customerName: 'Dewi Kusuma',
    customerPhone: '081234561002',
    serviceName: 'Make Up Natural',
    categoryName: 'Make Up',
    stylistName: 'Maya Putri',
    stylistInitials: 'MP',
    stylistColor: '#FF6B9D',
    date: _TODAY,
    timeSlot: '10:00:00',
    endTime: '11:00:00',
    duration: 60,
    price: 200000,
    status: 'UPCOMING',
    visitorType: 'BOOKING',
    paymentStatus: 'DEPOSIT',
    addOns: [],
    notes: '',
  },
  {
    id: 'dummy-3',
    bookingCode: 'WI-D003',
    customerName: 'Rina Marlina',
    customerPhone: '081234561003',
    serviceName: 'Creambath',
    categoryName: 'Hair',
    stylistName: 'Maya Putri',
    stylistInitials: 'MP',
    stylistColor: '#FF6B9D',
    date: _TODAY,
    timeSlot: '11:00:00',
    endTime: '12:00:00',
    duration: 60,
    price: 120000,
    status: 'IN_PROGRESS',
    visitorType: 'WALK_IN',
    paymentStatus: 'UNPAID',
    addOns: [],
    notes: 'Walk-in',
  },
  {
    id: 'dummy-4',
    bookingCode: 'WI-D004',
    customerName: 'Aulia Putri',
    customerPhone: '081234561004',
    serviceName: 'Facial Basic',
    categoryName: 'Face',
    stylistName: 'Maya Putri',
    stylistInitials: 'MP',
    stylistColor: '#FF6B9D',
    date: _TODAY,
    timeSlot: '13:00:00',
    endTime: '14:00:00',
    duration: 60,
    price: 150000,
    status: 'CONFIRMED',
    visitorType: 'WALK_IN',
    paymentStatus: 'UNPAID',
    addOns: [],
    notes: 'Walk-in',
  },
  {
    id: 'dummy-5',
    bookingCode: 'BK-D005',
    customerName: 'Nisa Amalia',
    customerPhone: '081234561005',
    serviceName: 'Keratin Treatment',
    categoryName: 'Hair',
    stylistName: 'Maya Putri',
    stylistInitials: 'MP',
    stylistColor: '#FF6B9D',
    date: _TODAY,
    timeSlot: '14:00:00',
    endTime: '16:00:00',
    duration: 120,
    price: 350000,
    status: 'COMPLETED',
    visitorType: 'BOOKING',
    paymentStatus: 'PAID',
    addOns: [],
    notes: '',
  },
  {
    id: 'dummy-6',
    bookingCode: 'BK-D006',
    customerName: 'Mega Wulandari',
    customerPhone: '081234561006',
    serviceName: 'Nail Art',
    categoryName: 'Nail',
    stylistName: 'Maya Putri',
    stylistInitials: 'MP',
    stylistColor: '#FF6B9D',
    date: _TODAY,
    timeSlot: '15:00:00',
    endTime: '16:00:00',
    duration: 60,
    price: 95000,
    status: 'UPCOMING',
    visitorType: 'BOOKING',
    paymentStatus: 'DEPOSIT',
    addOns: [],
    notes: '',
  },
  {
    id: 'dummy-7',
    bookingCode: 'WI-D007',
    customerName: 'Fitri Handayani',
    customerPhone: '081234561007',
    serviceName: 'Body Massage',
    categoryName: 'Massage',
    stylistName: 'Maya Putri',
    stylistInitials: 'MP',
    stylistColor: '#FF6B9D',
    date: _TODAY,
    timeSlot: '16:00:00',
    endTime: '17:00:00',
    duration: 60,
    price: 180000,
    status: 'CONFIRMED',
    visitorType: 'WALK_IN',
    paymentStatus: 'UNPAID',
    addOns: [],
    notes: 'Walk-in',
  },
];

export const MOCK_SERVICES: MockService[] = [
  { id: 'sv1', name: 'Ladies Haircut', categoryName: 'Hair', price: 150000, duration: 30 },
  { id: 'sv2', name: 'Ladies Haircut+Wash', categoryName: 'Hair', price: 180000, duration: 45 },
  {
    id: 'sv3',
    name: 'Ladies Hair Wash+Blowdry',
    categoryName: 'Hair',
    price: 100000,
    duration: 30,
  },
  { id: 'sv4', name: 'Keratin Treatment', categoryName: 'Hair', price: 500000, duration: 120 },
  { id: 'sv5', name: 'Color Treatment', categoryName: 'Colour', price: 300000, duration: 75 },
  { id: 'sv6', name: 'Balayage', categoryName: 'Colour', price: 450000, duration: 90 },
  { id: 'sv7', name: 'Facial Basic', categoryName: 'Face', price: 150000, duration: 60 },
  { id: 'sv8', name: 'Eyelash Extension', categoryName: 'Face', price: 200000, duration: 90 },
  { id: 'sv9', name: 'Gel Manicure', categoryName: 'Nail', price: 120000, duration: 45 },
  { id: 'sv10', name: 'Nail Art Basic', categoryName: 'Nail', price: 80000, duration: 30 },
  { id: 'sv11', name: 'Stone Massage', categoryName: 'Massage', price: 250000, duration: 60 },
  {
    id: 'sv12',
    name: 'Aromatherapy Massage',
    categoryName: 'Massage',
    price: 200000,
    duration: 60,
  },
];

export const MOCK_PRODUCTS: MockProduct[] = [
  { id: 'pr1', name: 'Hair Mask', price: 50000 },
  { id: 'pr2', name: 'Scalp Treatment', price: 75000 },
  { id: 'pr3', name: 'Deep Conditioning', price: 60000 },
  { id: 'pr4', name: 'Nail Art', price: 30000 },
  { id: 'pr5', name: 'Cuticle Treatment', price: 25000 },
  { id: 'pr6', name: 'Paraffin Wax', price: 35000 },
  { id: 'pr7', name: 'Collagen Mask', price: 80000 },
  { id: 'pr8', name: 'Serum Treatment', price: 45000 },
];
