// Operational Domain — canonical source of truth.
// All controller, component, and tRPC code must import from this file.
// No duplicate type definitions are allowed elsewhere.
//
// DB column mapping:
//   business_hours        → BusinessHoursDay
//   special_closing_dates → SpecialClosingDate
//   booking_policies      → BookingPolicy  (table does not yet exist — Phase 2)

// ── DayOfWeek ─────────────────────────────────────────────────────────────────

/**
 * Day of week index.
 *
 * Uses JavaScript Date.prototype.getDay() convention — NOT ISO 8601.
 *
 *   0 = Sunday    (Minggu)
 *   1 = Monday    (Senin)
 *   2 = Tuesday   (Selasa)
 *   3 = Wednesday (Rabu)
 *   4 = Thursday  (Kamis)
 *   5 = Friday    (Jumat)
 *   6 = Saturday  (Sabtu)
 *
 * This matches:
 *   - JavaScript Date.getDay()
 *   - date-fns getDay()
 *   - Supabase business_hours.day_of_week (integer 0-6)
 *   - customer/lib/date-utils.ts buildCalendarGrid()
 *   - customer/lib/validation.ts validateDateNotClosed()
 */
export type DayOfWeek = 0 | 1 | 2 | 3 | 4 | 5 | 6;

export const DAY_LABELS: Record<DayOfWeek, string> = {
  0: 'Minggu',
  1: 'Senin',
  2: 'Selasa',
  3: 'Rabu',
  4: 'Kamis',
  5: 'Jumat',
  6: 'Sabtu',
};

/** All seven days in display order (Senin first, Minggu last). */
export const WEEK_DAYS_ORDERED: DayOfWeek[] = [1, 2, 3, 4, 5, 6, 0];

// ── Slot Interval ─────────────────────────────────────────────────────────────

/**
 * Granularity of time slots offered to customers (minutes).
 * Stored in booking_policies.slot_interval_minutes.
 *
 * 15 — quarter-hour (high-density, short services)
 * 30 — half-hour (default for most salons)
 * 45 — three-quarter hour
 * 60 — hourly
 *
 * Changing this value affects the slot picker in the customer app.
 * Phase 1: stored in mock state only. Phase 2: written to Supabase,
 * customer slot generator reads this instead of SESSION_TIMES constant.
 */
export type SlotIntervalMinutes = 15 | 30 | 45 | 60;

// ── Business Hours ────────────────────────────────────────────────────────────

/**
 * Opening hours for one day of the week.
 * Maps 1:1 to a row in the Supabase business_hours table.
 *
 * DB columns:
 *   day_of_week  INTEGER     → dayOfWeek
 *   is_closed    BOOLEAN     → isClosed
 *   open_time    TIME        → openTime  ("HH:MM:SS" from Postgres, normalise to "HH:mm")
 *   close_time   TIME        → closeTime ("HH:MM:SS" from Postgres, normalise to "HH:mm")
 *   salon_id     UUID        → not in this type (added by tRPC layer)
 */
export interface BusinessHoursDay {
  dayOfWeek: DayOfWeek;

  /**
   * Uses isClosed — NOT isOpen — to match Supabase column is_closed exactly.
   *
   * true  = salon closed on this day (customer cannot book)
   * false = salon open; openTime and closeTime are valid
   */
  isClosed: boolean;

  /**
   * Opening time in "HH:mm" format (24-hour clock).
   *
   * null  — only when isClosed is true.
   * When isClosed is toggled back to false, retain the last value rather
   * than resetting to null. This preserves owner's previous configuration.
   *
   * When reading from Supabase: trim seconds — "09:00:00" → "09:00".
   * When writing to Supabase: "HH:mm" is accepted by Postgres TIME columns.
   */
  openTime: string | null;

  /**
   * Closing time in "HH:mm" format (24-hour clock).
   * Same rules as openTime.
   *
   * Guard: do not persist to Supabase if isClosed=false and closeTime is null.
   */
  closeTime: string | null;
}

// ── Special Closing Dates ─────────────────────────────────────────────────────

/**
 * A specific calendar date on which the salon is closed.
 * Overrides BusinessHoursDay — if a date appears here the salon is closed
 * regardless of the day-of-week schedule.
 *
 * Maps to the special_closing_dates table (Phase 2 — does not yet exist).
 *
 * DB columns (planned):
 *   id         UUID  → id
 *   date       DATE  → date  ("YYYY-MM-DD")
 *   label      TEXT  → label (non-empty)
 *   salon_id   UUID  → not in this type
 */
export interface SpecialClosingDate {
  /**
   * UUID. Generated by the controller (crypto.randomUUID()), not by the UI.
   * Used as the stable key for remove operations.
   */
  id: string;

  /**
   * ISO date string: "YYYY-MM-DD". No time component. No timezone offset.
   *
   * IMPORTANT: always parse as local time — use new Date(date + 'T00:00:00'),
   * never new Date(date). An ISO date string without a time component is
   * treated as UTC by the JS Date constructor, which shifts the date by the
   * local timezone offset (e.g. in GMT+7 "2026-08-17" becomes 2026-08-16T17:00 local).
   */
  date: string;

  /**
   * Human-readable reason for the closure. Required, non-empty.
   * Default value in the add form: "Hari Libur".
   *
   * Displayed only in the owner dashboard (not shown to customers).
   * Prevents ambiguous rows with no context months later.
   */
  label: string;
}

// ── Booking Policy ────────────────────────────────────────────────────────────

/**
 * Salon-level rules that govern when and how customers can book.
 * One policy per salon (unique constraint on salon_id).
 *
 * Maps to the booking_policies table (Phase 2 — does not yet exist).
 *
 * DB columns (planned):
 *   slot_interval_minutes     SMALLINT  → slotIntervalMinutes
 *   lead_time_hours           SMALLINT  → leadTimeHours
 *   advance_booking_days      SMALLINT  → advanceBookingDays
 *   cancellation_window_hours SMALLINT  → cancellationWindowHours
 *
 * Phase 1: mock in-memory only, no Supabase write.
 * Phase 2: tRPC upsert mutation, customer app reads via useBookingPolicy hook.
 */
export interface BookingPolicy {
  /**
   * Interval between time slots shown to customers.
   * Default: 30.
   *
   * Phase 1: stored in mock state only.
   * Phase 2: customer slot generator replaces SESSION_TIMES hardcode with
   * this value (booking.constants.ts SESSION_TIMES will be removed).
   */
  slotIntervalMinutes: SlotIntervalMinutes;

  /**
   * Minimum hours before a service time that a customer may still book.
   * Range: 0–24.
   *   0  = no minimum (last-minute bookings allowed)
   *   2  = customer must book at least 2 hours ahead (default)
   *   24 = customer must book at least 1 day ahead
   *
   * Phase 2: customer slot picker disables slots within this window.
   */
  leadTimeHours: number;

  /**
   * Maximum days into the future a customer may book.
   * Range: 1–90.
   *   1  = same-day / next-day only
   *   30 = up to 30 days ahead (default)
   *   90 = up to 3 months ahead
   *
   * Phase 2: customer date picker disables dates beyond this window.
   */
  advanceBookingDays: number;

  /**
   * Minimum hours before a service time within which a customer may cancel.
   * Range: 0–48.
   *   0  = customer may cancel at any time (default)
   *   2  = customer must cancel at least 2 hours before
   *   24 = customer must cancel at least 1 day before
   *
   * Phase 2: used by the cancellation flow (does not yet exist in customer app).
   */
  cancellationWindowHours: number;
}

// ── Operational Settings (domain aggregate) ───────────────────────────────────

/**
 * Full operational configuration for one salon.
 * This is the top-level type used by useOperasionalController.
 *
 * businessHours       — always contains exactly 7 entries, one per DayOfWeek.
 *                       Ordered by dayOfWeek ascending (0=Sunday first).
 *                       Matches Supabase ORDER BY day_of_week ASC.
 *
 * specialClosingDates — variable-length list. UI displays sorted ascending
 *                       by date (soonest first). Sorting is the controller's
 *                       responsibility, not enforced by this type.
 *
 * bookingPolicy       — single flat object (not an array).
 */
export interface OperationalSettings {
  businessHours: BusinessHoursDay[];
  specialClosingDates: SpecialClosingDate[];
  bookingPolicy: BookingPolicy;
}

// ── Default Values ────────────────────────────────────────────────────────────

/**
 * Seed values used by the mock controller (Phase 1).
 * Reflects a realistic small-to-medium Indonesian salon:
 *   - Mon–Fri: 09:00–20:00
 *   - Saturday: 09:00–18:00
 *   - Sunday: closed
 *
 * These defaults are also used as fallback when Supabase returns no rows
 * for a salon that has not yet configured its operational settings.
 */
export const DEFAULT_BUSINESS_HOURS: BusinessHoursDay[] = [
  { dayOfWeek: 0, isClosed: true, openTime: null, closeTime: null }, // Minggu
  { dayOfWeek: 1, isClosed: false, openTime: '09:00', closeTime: '20:00' }, // Senin
  { dayOfWeek: 2, isClosed: false, openTime: '09:00', closeTime: '20:00' }, // Selasa
  { dayOfWeek: 3, isClosed: false, openTime: '09:00', closeTime: '20:00' }, // Rabu
  { dayOfWeek: 4, isClosed: false, openTime: '09:00', closeTime: '20:00' }, // Kamis
  { dayOfWeek: 5, isClosed: false, openTime: '09:00', closeTime: '20:00' }, // Jumat
  { dayOfWeek: 6, isClosed: false, openTime: '09:00', closeTime: '18:00' }, // Sabtu
];

export const DEFAULT_BOOKING_POLICY: BookingPolicy = {
  slotIntervalMinutes: 30,
  leadTimeHours: 2,
  advanceBookingDays: 30,
  cancellationWindowHours: 2,
};
